#!/bin/bash

#The script prompts you for commit message, adds and pushes

read -p "Enter the commit message: " MESSAGE
git add .
git commit -m '$MESSAGE'
git push

#inputs the username stored in variable $GITUSER
expect "Username': "

cript inputs the password stored in variable $GITPASS
while true; do
if [[ $tail -n 1 done) == *"Password for 'https://$GITUSER@github.com': "* ]]; then
echo $GITPASS >> done
fi
sleep 1
done
